# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
