# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='negative_qualities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='positive_qualities',
            field=models.TextField(blank=True),
        ),
    ]
